### PR TITLE
Fix discrete convergence problems

### PR DESCRIPTION
**Pull request by franknoe**
Fixes same important problems that prevented MLHMM for discrete HMMs to converge for long lag times.

### CODE REVIEW

**Comment by jchodera** [comment]
Thanks!  Let's let the travis checks run before merging.

**Comment by franknoe** [comment]
Did that work?

Am 24/03/15 um 04:07 schrieb John Chodera:

> Thanks! Let's let the travis checks run before merging.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/choderalab/bhmm/pull/16#issuecomment-85319264.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by jchodera** [comment]
All is good!  Merging!

**Comment by franknoe** [comment]
yay! thanks!!!

Am 26/03/15 um 22:39 schrieb John Chodera:

> All is good! Merging!
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/choderalab/bhmm/pull/16#issuecomment-86728854.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Pull request merged**
