### PR TITLE
Hmm initialization

### PR DESCRIPTION
**Pull request by franknoe**
Sorry for being out of sync - there are many changes in this branch.

### CODE REVIEW

**Comment by jchodera** [comment]
Thanks!  Should I review this ASAP so we can commit and move on, or do I have a bit of time to look through the changes?

**Comment by franknoe** [comment]
You have time. We can chat on tuesday, when I'm in Houston.

Am 19/03/15 um 16:57 schrieb John Chodera:

> Thanks! Should I review this ASAP so we can commit and move on, or do 
> I have a bit of time to look through the changes?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/choderalab/bhmm/pull/14#issuecomment-83642708.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by jchodera** [comment]
Great, thanks!

**Comment by jchodera** [comment]
Looks like `pyemma` has been added to `setup.py`, but not to the conda recipe requirements [`devtools/conda-recipe/meta.yaml`](https://github.com/choderalab/bhmm/blob/hmm_initialization/devtools/conda-recipe/meta.yaml#L9-L20).

Can you add the specific version requirement for `pyemma` there?

**Comment by jchodera** [comment]
See the `requirements` section of the documentation for conda recipes here:
http://conda.pydata.org/docs/build.html

I think you want to add

```
  - pyemma >=1.1.2
```

**Comment by jchodera** [comment]
Only pyemma 1.1.1 is up on binstar, though:
https://binstar.org/omnia/pyemma/files

Does the [pyemma recipe](https://github.com/omnia-md/conda-recipes/blob/master/pyemma/meta.yaml) need to be updated by @marscher?

**Comment by franknoe** [comment]
I think Martin needs to send a pull request for omnia. It's version 1.1.2

Am 19/03/15 um 17:24 schrieb John Chodera:

> Looks like |pyemma| has been added to |setup.py|, but not to the conda 
> recipe requirements |devtools/conda-recipe/meta.yaml| 
> https://github.com/choderalab/bhmm/blob/hmm_initialization/devtools/conda-recipe/meta.yaml#L9-L20.
> 
> Can you add the specific version requirement for |pyemma| there?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/choderalab/bhmm/pull/14#issuecomment-83650657.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
yes.

Am 19/03/15 um 17:27 schrieb John Chodera:

> Only pyemma 1.1.1 is up on binstar, though:
> https://binstar.org/omnia/pyemma/files
> 
> Does the pyemma recipe 
> https://github.com/omnia-md/conda-recipes/blob/master/pyemma/meta.yaml 
> need to be updated by @marscher https://github.com/marscher?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/choderalab/bhmm/pull/14#issuecomment-83651279.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by jchodera** [comment]
Merging this, and will fix issues starting from here!

**Pull request merged**
