### PR TITLE
Addition of C extensions and tests

### PR DESCRIPTION
**Pull request by jchodera**
This is @franknoe's addition of C extensions and tests.

### CODE REVIEW

**Comment by jchodera** [comment]
@franknoe : There seems to be a problem with imports:
https://travis-ci.org/choderalab/bhmm/builds/54006305#L836-L848

```
Traceback (most recent call last):
  File "/home/travis/miniconda/conda-bld/test-tmp_dir/run_test.py", line 25, in <module>
    import bhmm
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/bhmm-0.1.0-py2.7-linux-x86_64.egg/bhmm/__init__.py", line 12, in <module>
    from hmm_class import HMM
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/bhmm-0.1.0-py2.7-linux-x86_64.egg/bhmm/hmm_class.py", line 8, in <module>
    import output_models
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/bhmm-0.1.0-py2.7-linux-x86_64.egg/bhmm/output_models/__init__.py", line 5, in <module>
    from gaussian import GaussianOutputModel
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/bhmm-0.1.0-py2.7-linux-x86_64.egg/bhmm/output_models/gaussian.py", line 5, in <module>
    import impl_c.gaussian as gc
ImportError: No module named impl_c.gaussian
```

I think this just needs you to add the `impl_*` packages to `setup.py` in the `packages` line, to change it from

```
packages=['bhmm', 'bhmm.msm', 'bhmm.hidden', 'bhmm.ml', 'bhmm.msm', 'bhmm.output_models', 'bhmm.util'],
```

to:

```
packages=['bhmm', 'bhmm.msm', 'bhmm.hidden', 'bhmm.ml', 'bhmm.msm', 'bhmm.output_models', 'bhmm.util', 'bhmm.hidden.impl_python', 'bhmm.hidden.impl_c'],
```

Once you make this change, I think it should work!

**Comment by franknoe** [comment]
Done and pushed. Thanks!

Am 12/03/15 um 15:54 schrieb John Chodera:

> @franknoe https://github.com/franknoe : There seems to be a problem 
> with imports:
> https://travis-ci.org/choderalab/bhmm/builds/54006305#L836-L848
> 
> |Traceback (most recent call last):
>    File "/home/travis/miniconda/conda-bld/test-tmp_dir/run_test.py", line 25, in <module>
>      import bhmm
>    File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/bhmm-0.1.0-py2.7-linux-x86_64.egg/bhmm/__init__.py", line 12, in <module>
>      from hmm_class import HMM
>    File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/bhmm-0.1.0-py2.7-linux-x86_64.egg/bhmm/hmm_class.py", line 8, in <module>
>      import output_models
>    File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/bhmm-0.1.0-py2.7-linux-x86_64.egg/bhmm/output_models/__init__.py", line 5, in <module>
>      from gaussian import GaussianOutputModel
>    File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/bhmm-0.1.0-py2.7-linux-x86_64.egg/bhmm/output_models/gaussian.py", line 5, in <module>
>      import impl_c.gaussian as gc
> ImportError: No module named impl_c.gaussian
> |
> 
> I think this just needs you to add the |impl_*| packages to |setup.py| 
> in the |packages| line, to change it from
> 
> |packages=['bhmm', 'bhmm.msm', 'bhmm.hidden', 'bhmm.ml', 'bhmm.msm', 'bhmm.output_models', 'bhmm.util'],
> |
> 
> to:
> 
> |packages=['bhmm', 'bhmm.msm', 'bhmm.hidden', 'bhmm.ml', 'bhmm.msm', 'bhmm.output_models', 'bhmm.util', 'bhmm.hidden.impl_python', 'bhmm.hidden.impl_c'],
> |
> 
> Once you make this change, I think it should work!
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/choderalab/bhmm/pull/8#issuecomment-78495558.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by jchodera** [comment]
Thanks!  Will just wait for tests to finish before merging.

**Comment by jchodera** [comment]
OK, there are still issues, but I will merge and take it from here to fix them!

**Comment by franknoe** [comment]
thanks

Am 12/03/15 um 19:17 schrieb John Chodera:

> OK, there are still issues, but I will merge and take it from here to 
> fix them!
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/choderalab/bhmm/pull/8#issuecomment-78553591.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Pull request merged**
