### PR TITLE
Updating manuscript with updated examples

### PR DESCRIPTION
**Pull request by jchodera**
Working on updating the manuscript with latest examples.

### CODE REVIEW

**Comment by jchodera** [comment]
The automatic LaTeX table generation is pretty awesome, but I will need to generate a special table to replace the table in the paper for the synthetic three-state example.  I've renamed the command-line executable script as `synthetic-example.py` and added a `README.md` to this example.  `generate-figure.py` will be modified to generate the figure and table data needed for the paper.

**Comment by franknoe** [comment]
ok

Am 17/05/15 um 22:14 schrieb John Chodera:

> The automatic LaTeX table generation is pretty awesome, but I will 
> need to generate a special table to replace the table in the paper for 
> the synthetic three-state example. I've renamed the command-line 
> executable script as |synthetic-example.py| and added a |README.md| to 
> this example. |generate-figure.py| will be modified to generate the 
> figure and table data needed for the paper.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/bhmm/bhmm/pull/36#issuecomment-102846527.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by jchodera** [comment]
I've revised the synthetic three-state model, but both the MLHMM and 1000 cycles of BHMM sampling seems to converge to a different model than the true model.  Could you take a look at Table I in the updated manuscript here, @franknoe?  Is my revised `examples/synthetic-three-state-model/generate-figure.py` script using the BHMM sampling or analysis incorrectly?

**Comment by franknoe** [comment]
I'll check later today, but my day is very full, so it will take a while

Am 18/05/15 um 06:30 schrieb John Chodera:

> I've revised the synthetic three-state model, but both the MLHMM and 
> 1000 cycles of BHMM sampling seems to converge to a different model 
> than the true model. Could you take a look at Table I in the updated 
> manuscript here, @franknoe https://github.com/franknoe? Is my 
> revised |examples/synthetic-three-state-model/generate-figure.py| 
> script using the BHMM sampling or analysis incorrectly?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/bhmm/bhmm/pull/36#issuecomment-102919682.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
Looks good to me. Below find the true model, the MLE and the BHMM 
results after 100 steps.
As far as I can see all quantities except are within 2-sigma 
uncertainties. Perhaps you got confused because the order of states has 
changed? I believe this happens in the Gaussian mixture model estimation.

## True model

nstates: 3
Tij:
[[ 0.989  0.01   0.001]
  [ 0.01   0.94   0.05 ]
  [ 0.001  0.05   0.949]]
Pi:
[ 0.33333333  0.33333333  0.33333333]

## output model:

GaussianOutputModel
nstates: 3
means: [ 3.   4.7  5.6]

## sigmas: [ 1.   0.3  0.2]

maximum likelihood HMM:

## [NOW STATE ORDER IS 0,2,1]

nstates: 3
Tij:
[[ 0.98939172  0.0010516   0.00955668]
  [ 0.00106617  0.9473462   0.05158762]
  [ 0.00945983  0.05036699  0.94017318]]
Pi:
[ 0.33371472  0.32915414  0.33713114]

## output model:

GaussianOutputModel
nstates: 3
means: [ 3.00233317  5.59881947  4.7001064 ]

## sigmas: [ 0.99818006  0.19798731  0.29827076]

BHMM:
[NOW STATE ORDER IS 0,2,1]

Am 18/05/15 um 06:30 schrieb John Chodera:

> I've revised the synthetic three-state model, but both the MLHMM and 
> 1000 cycles of BHMM sampling seems to converge to a different model 
> than the true model. Could you take a look at Table I in the updated 
> manuscript here, @franknoe https://github.com/franknoe? Is my 
> revised |examples/synthetic-three-state-model/generate-figure.py| 
> script using the BHMM sampling or analysis incorrectly?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/bhmm/bhmm/pull/36#issuecomment-102919682.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by jchodera** [comment]
Merging.

**Pull request merged**
