### PR TITLE
changed all relative imports to absolute imports

### PR DESCRIPTION
**Pull request by franknoe**
Changed all imports to be absolute. However, the same problem persists.

I can execute the nosetests as follows without any error:

```
nosetests bhmm --nocapture --verbosity=2 --with-doctest
```

But the following test run raises lots of import errors that make no sense to me,

```
conda build devtools/conda-recipe/
```

including:

```
/bhmm/api.py", line 6, in <module>
    from bhmm.hmm.generic_hmm import HMM as _HMM
ImportError: No module named hmm.generic_hmm
```

No idea what the problem is, because I can use the bhmm package from python or ipython without problems... Any ideas?

### CODE REVIEW

**Comment by jchodera** [comment]
Awesome!  If this fixes the nosetests, I can take it from here and debug the conda recipe.

**Comment by franknoe** [comment]
Thanks. Please check the conda recipe - I think there are lots of 
dependencies that are not actually needed, at least not for running.

Am 05/05/15 um 21:51 schrieb John Chodera:

> Awesome! If this fixes the nosetests, I can take it from here and 
> debug the conda recipe.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/bhmm/bhmm/pull/21#issuecomment-99201608.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
Oh, and pyemma needs to become >=1.2. In short, I believe in 
conda-recipe/meta.yaml it should be:

run:
     - python
     - numpy
     - scipy
     - scikit-learn
     - pyemma >=1.2

I think we need none of the following packages to run:
     - cython
     - docopt
     - pyyaml
     - jinja2
     - matplotlib
     - seaborn

Am 05/05/15 um 21:51 schrieb John Chodera:

> Awesome! If this fixes the nosetests, I can take it from here and 
> debug the conda recipe.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/bhmm/bhmm/pull/21#issuecomment-99201608.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by jchodera** [comment]
I started updating the main recipe here:
https://github.com/omnia-md/conda-recipes/tree/master/bhmm

I'll backport those changes.

Not sure why travis isn't building and testing this PR.  It could be that it stopped working after the migration to the `bhmm` org.  I'll merge this and then work on getting travis to work again.

**Pull request merged**
